"Battle Royale",
"Hide and Seek",
"The Bridge",
"The Pit",
"Skywars",
"Build Battle Solo",
"Build Battle Teams",
"Guess The Build",
"Build Battle Pro Mode",
"Turbo Kart Racers",
"The Walls",
"Arena Brawl",
"Paintball",
"Quakecraft",
"VampireZ",
"Murder Mystery",
"UHC Duels",
"Skywars Duels",
"Duels",
"OP Duels",
"Duel Tournament",
"Smash Heros",
"Speed UHC",
"Warlords",
"Crazy Walls",
"Cops and Crims",
"Mini Walls",
"UHC Champions",
"Blitz Survival Games",
"Mega Walls",
"Sky Clash",
"Player Housing",
"PvP Run",
"TNT Run",
"Bow Spleef",
"TNT Tag",
"TNT Wizards",
"Blocking Dead",
"Hypixel Says",
"Farm Hunt",
"Creeper Attack",
"Party Games",
"Hole In The Wall",
"FootBall",
"Pixel Painters",
"Bounty Hunters",
"Dragon Wars",
"Ender Spleef",
"Galaxy Wars",
"Throw Out",
"Zombies">;